object Versions {
    const val GRADLE = "7.0.2"
    const val KOTLIN = "1.5.21"
    const val GOOGLE_SERVICES = "4.3.10"
    const val CORE_KTX = "1.6.0"
    const val APPCOMPAT = "1.3.1"
    const val LIVEDATA_KTX = "2.4.0-alpha03"
    const val MATERIAL = "1.4.0"
    const val LOTTIE = "4.1.0"
    const val HILT = "2.38.1"
    const val COROUTINES = "1.5.1-native-mt"
    const val FIREBASE_BOM = "28.2.1"
    const val FIREBASE_AUTH = "21.0.1"
    const val FIREBASE_FIRESTORE = "23.0.3"
    const val NAVIGATION = "2.3.5"
    const val LEAKCANARY = "2.7"
    const val JUNIT = "4.13.2"
    const val TRUTH = "1.1.3"
}
